name: DeployAdlsUat
env:
  azureRegion: East US 2
  subscriptionId: ${{ secrets.SUB_SANDBOX_2 }}  # uat subscription
  resourceGroupName: DataLakeStorage
  templateFile: ./Adls/adls.bicep
  parametersFile: ./Adls/adls-uat.parameters.jsonc

# Controls when the workflow will run
on:
  # Workflow will run on upon a commit
  push:
    branches:
      - main
    paths:
      - "Adls/**.bicep"
      - "Adls/**.json"
      - "Adls/**.jsonc"

  # Workflow can be triggered manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Azure/login@v1
        name: Login to Azure
        with:
          creds: ${{ secrets.AZURE_CREDS }}
      
      - uses: Azure/arm-deploy@v1
        name: Deploy bicep file
        with:
          scope: subscription
          deploymentName: 'Github.Actions-${{ github.workflow }}-${{ github.run_number }}'
          subscriptionId: ${{ env.subscriptionId }}
          resourceGroupName: ${{ env.resourceGroupName }}
          region: ${{env.azureRegion }}
          template: ${{env.templateFile }}
          parameters: ${{ env.parametersFile}}