# This is a basic workflow to help you get started with Actions

name: Deploy RG
env:
  azureRegion: East US 2
  subscriptionId: fac1ea11-e5a7-4e74-8d7e-965344c54f56 # Bakunas Sandbox 3
  networkResourceGroupName: Test-01

# Controls when the workflow will run
on:
  push:
    branches:
      - master
    paths:
      - "Testing/**"
  workflow_dispatch:


jobs:
  armDeploy:
    name: Deploy ARM Templates
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}
      
      - name: Deploy Resource Group ${{ env.networkResourceGroupName }}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscriptionId }}
          region: ${{ env.azureRegion }}
          template: ./Testing/ResourceGroup.json
          parameters:
            resourceGroup_Name=${{ env.networkResourceGroupName }}
          deploymentName: ResourceGroupDeploy-${{ env.networkResourceGroupName }}

